import { PERMISSIONS, type AuthUser } from "@hotel/shared";

type UserLike = Pick<AuthUser, "permissions"> | null;

export function getMaintenanceAccess(user: UserLike) {
  const permissions = user?.permissions || [];
  const has = (permission: (typeof PERMISSIONS)[keyof typeof PERMISSIONS]) =>
    permissions.includes(permission);
  return {
    canEnter: [
      PERMISSIONS.MAINTENANCE_OCCURRENCE_CREATE,
      PERMISSIONS.MAINTENANCE_READ,
      PERMISSIONS.MAINTENANCE_TRIAGE,
      PERMISSIONS.MAINTENANCE_EXECUTE,
      PERMISSIONS.MAINTENANCE_BLOCK_MANAGE,
      PERMISSIONS.MAINTENANCE_INSPECT,
      PERMISSIONS.MAINTENANCE_LIABILITY_CONFIRM,
      PERMISSIONS.MAINTENANCE_CATALOG_MANAGE,
      PERMISSIONS.MAINTENANCE_FINANCE_READ,
      PERMISSIONS.MAINTENANCE_FINANCE_PROPOSE,
      PERMISSIONS.MAINTENANCE_FINANCE_APPROVE,
      PERMISSIONS.MAINTENANCE_FINANCE_SETTLE,
      PERMISSIONS.MAINTENANCE_PLAN_MANAGE,
      PERMISSIONS.MAINTENANCE_SLA_MANAGE,
      PERMISSIONS.MAINTENANCE_SUPPLIER_MANAGE,
      PERMISSIONS.MAINTENANCE_ANALYTICS_READ,
    ].some(has),
    canCreate: has(PERMISSIONS.MAINTENANCE_OCCURRENCE_CREATE),
    canRead: [
      PERMISSIONS.MAINTENANCE_READ,
      PERMISSIONS.MAINTENANCE_TRIAGE,
      PERMISSIONS.MAINTENANCE_EXECUTE,
      PERMISSIONS.MAINTENANCE_BLOCK_MANAGE,
      PERMISSIONS.MAINTENANCE_INSPECT,
      PERMISSIONS.MAINTENANCE_LIABILITY_CONFIRM,
    ].some(has),
    canTriage: has(PERMISSIONS.MAINTENANCE_TRIAGE),
    canExecute: has(PERMISSIONS.MAINTENANCE_EXECUTE),
    canManageBlocks: has(PERMISSIONS.MAINTENANCE_BLOCK_MANAGE),
    canInspect: has(PERMISSIONS.MAINTENANCE_INSPECT),
    canConfirmLiability: has(PERMISSIONS.MAINTENANCE_LIABILITY_CONFIRM),
    canManageCatalogs: has(PERMISSIONS.MAINTENANCE_CATALOG_MANAGE),
    canReadFinance: has(PERMISSIONS.MAINTENANCE_FINANCE_READ),
    canProposeFinance: has(PERMISSIONS.MAINTENANCE_FINANCE_PROPOSE),
    canApproveFinance: has(PERMISSIONS.MAINTENANCE_FINANCE_APPROVE),
    canSettleFinance: has(PERMISSIONS.MAINTENANCE_FINANCE_SETTLE),
    canManagePlans: has(PERMISSIONS.MAINTENANCE_PLAN_MANAGE),
    canManageSla: has(PERMISSIONS.MAINTENANCE_SLA_MANAGE),
    canManageSuppliers: has(PERMISSIONS.MAINTENANCE_SUPPLIER_MANAGE),
    canReadAnalytics: has(PERMISSIONS.MAINTENANCE_ANALYTICS_READ),
  };
}
