import { PERMISSIONS, type AuthUser } from "@hotel/shared";

type UserLike = Pick<AuthUser, "permissions"> | null;

export function getMaintenanceAccess(user: UserLike) {
  const permissions = user?.permissions || [];
  const has = (permission: (typeof PERMISSIONS)[keyof typeof PERMISSIONS]) => permissions.includes(permission);
  return {
    canEnter: [
      PERMISSIONS.MAINTENANCE_OCCURRENCE_CREATE,
      PERMISSIONS.MAINTENANCE_READ,
      PERMISSIONS.MAINTENANCE_TRIAGE,
      PERMISSIONS.MAINTENANCE_EXECUTE,
      PERMISSIONS.MAINTENANCE_BLOCK_MANAGE,
      PERMISSIONS.MAINTENANCE_INSPECT,
      PERMISSIONS.MAINTENANCE_LIABILITY_CONFIRM,
      PERMISSIONS.MAINTENANCE_CATALOG_MANAGE
    ].some(has),
    canCreate: has(PERMISSIONS.MAINTENANCE_OCCURRENCE_CREATE),
    canRead: [PERMISSIONS.MAINTENANCE_READ, PERMISSIONS.MAINTENANCE_TRIAGE, PERMISSIONS.MAINTENANCE_EXECUTE, PERMISSIONS.MAINTENANCE_BLOCK_MANAGE, PERMISSIONS.MAINTENANCE_INSPECT, PERMISSIONS.MAINTENANCE_LIABILITY_CONFIRM].some(has),
    canTriage: has(PERMISSIONS.MAINTENANCE_TRIAGE),
    canExecute: has(PERMISSIONS.MAINTENANCE_EXECUTE),
    canManageBlocks: has(PERMISSIONS.MAINTENANCE_BLOCK_MANAGE),
    canInspect: has(PERMISSIONS.MAINTENANCE_INSPECT),
    canConfirmLiability: has(PERMISSIONS.MAINTENANCE_LIABILITY_CONFIRM),
    canManageCatalogs: has(PERMISSIONS.MAINTENANCE_CATALOG_MANAGE)
  };
}
