export const PERMISSIONS = {
  HOTEL_CREATE: "create_hotel",
  HOTEL_READ: "read_hotel",
  HOTEL_UPDATE: "update_hotel",
  HOTEL_DELETE: "delete_hotel",
  ROOM_CREATE: "create_room",
  ROOM_READ: "read_room",
  ROOM_UPDATE: "update_room",
  ROOM_DELETE: "delete_room",
  CUSTOMER_CREATE: "create_customer",
  CUSTOMER_READ: "read_customer",
  CUSTOMER_UPDATE: "update_customer",
  CUSTOMER_DELETE: "delete_customer",
  RESERVATION_CREATE: "create_reservation",
  RESERVATION_READ: "read_reservation",
  RESERVATION_UPDATE: "update_reservation",
  RESERVATION_DELETE: "delete_reservation",
  RESERVATIONS_CALENDAR_ACCESS: "access_reservations_calendar",
  TRANSACTION_CREATE: "create_transactions",
  TRANSACTION_READ: "read_transactions",
  TRANSACTION_UPDATE: "update_transactions",
  TRANSACTION_DELETE: "delete_transactions",
  PRODUCT_CREATE: "create_product",
  PRODUCT_READ: "read_product",
  PRODUCT_UPDATE: "update_product",
  PRODUCT_DELETE: "delete_product",
  CONSUMPTION_READ: "read_consumption",
  CONSUMPTION_SETTINGS_MANAGE: "manage_consumption_settings",
  CONSUMPTION_POST: "post_consumption",
  CONSUMPTION_PAYMENT_RECEIVE: "receive_consumption_payment",
  CONSUMPTION_COURTESY_GRANT: "grant_consumption_courtesy",
  CONSUMPTION_VOID: "void_consumption",
  CONSUMPTION_ADJUSTMENT_APPROVE: "approve_consumption_adjustment",
  CONSUMPTION_SERVICE_MANAGE: "manage_consumption_service",
  CONSUMPTION_SERVICE_CANCEL: "cancel_consumption_service",
  STAY_PAYERS_MANAGE: "manage_stay_payers",
  CORPORATE_ACCOUNTS_MANAGE: "manage_corporate_accounts",
  CORPORATE_CREDIT_REQUEST: "request_corporate_credit",
  CORPORATE_CREDIT_APPROVE: "approve_corporate_credit",
  CORPORATE_RECEIVABLES_SETTLE: "settle_corporate_receivables",
  CONSUMPTION_BENEFITS_MANAGE: "manage_consumption_benefits",
  CONSUMPTION_BENEFITS_OVERRIDE: "override_consumption_benefits",
  CONSUMPTION_TRANSFER: "transfer_consumption",
  POST_CHECKOUT_CONSUMPTION_REVIEW: "review_post_checkout_consumption",
  POST_CHECKOUT_CONSUMPTION_WAIVE: "waive_post_checkout_consumption",
  COMMERCIAL_PARTNERS_READ: "read_commercial_partners",
  COMMERCIAL_PARTNERS_MANAGE: "manage_commercial_partners",
  COMMERCIAL_AGREEMENTS_MANAGE: "manage_commercial_agreements",
  INVENTORY_READ: "read_inventory",
  INVENTORY_COSTS_READ: "read_inventory_costs",
  INVENTORY_SETTINGS_MANAGE: "manage_inventory_settings",
  INVENTORY_MOVEMENTS_POST: "post_inventory_movements",
  INVENTORY_COUNTS_PERFORM: "perform_inventory_counts",
  CONSUMPTION_ANALYTICS_READ: "read_consumption_analytics",
  PARTNER_SETTLEMENTS_READ: "read_partner_settlements",
  PARTNER_SETTLEMENTS_PREPARE: "prepare_partner_settlements",
  PARTNER_SETTLEMENTS_APPROVE: "approve_partner_settlements",
  PARTNER_SETTLEMENTS_SETTLE: "settle_partner_settlements",
  BUSINESS_ORGANIZATIONS_READ: "read_business_organizations",
  BUSINESS_ORGANIZATIONS_MANAGE: "manage_business_organizations",
  PROCUREMENT_READ: "read_procurement",
  PROCUREMENT_REQUEST: "request_procurement",
  PROCUREMENT_APPROVE: "approve_procurement",
  PROCUREMENT_RECEIVE: "receive_procurement",
  PROCUREMENT_INVOICES_REVIEW: "review_procurement_invoices",
  SUPPLIER_PAYABLES_SETTLE: "settle_supplier_payables",
  INVENTORY_LOTS_MANAGE: "manage_inventory_lots",
  MINIBAR_COMPOSITIONS_MANAGE: "manage_minibar_compositions",
  MINIBAR_REPLENISHMENT_EXECUTE: "execute_minibar_replenishment",
  CASH_MANAGEMENT_READ: "read_cash_management",
  CASH_REGISTER_OPERATE: "operate_cash_register",
  CASH_DIFFERENCES_APPROVE: "approve_cash_differences",
  DAILY_CLOSE_PREPARE: "prepare_daily_close",
  DAILY_CLOSE_APPROVE: "approve_daily_close",
  PARTNER_DISPUTES_MANAGE: "manage_partner_disputes",
  SEASON_CREATE: "create_season",
  SEASON_READ: "read_season",
  SEASON_UPDATE: "update_season",
  SEASON_DELETE: "delete_season",
  SEASON_ROOM_RATE_CREATE: "create_season_room_rate",
  SEASON_ROOM_RATE_READ: "read_season_room_rate",
  SEASON_ROOM_RATE_UPDATE: "update_season_room_rate",
  SEASON_ROOM_RATE_DELETE: "delete_season_room_rate",
  MAINTENANCE_OCCURRENCE_CREATE: "create_maintenance_occurrence",
  MAINTENANCE_READ: "read_maintenance",
  MAINTENANCE_TRIAGE: "triage_maintenance",
  MAINTENANCE_EXECUTE: "execute_maintenance",
  MAINTENANCE_BLOCK_MANAGE: "manage_maintenance_blocks",
  MAINTENANCE_INSPECT: "inspect_maintenance",
  MAINTENANCE_LIABILITY_CONFIRM: "confirm_damage_liability",
  MAINTENANCE_CATALOG_MANAGE: "manage_maintenance_catalogs",
  MAINTENANCE_FINANCE_READ: "read_maintenance_finance",
  MAINTENANCE_FINANCE_PROPOSE: "propose_maintenance_finance",
  MAINTENANCE_FINANCE_APPROVE: "approve_maintenance_finance",
  MAINTENANCE_FINANCE_SETTLE: "settle_maintenance_finance",
  MAINTENANCE_PLAN_MANAGE: "manage_maintenance_plans",
  MAINTENANCE_SLA_MANAGE: "manage_maintenance_sla",
  MAINTENANCE_SUPPLIER_MANAGE: "manage_maintenance_suppliers",
  MAINTENANCE_ANALYTICS_READ: "read_maintenance_analytics",
  MAINTENANCE_TEAMS_MANAGE: "manage_maintenance_teams",
  MAINTENANCE_SCHEDULE_MANAGE: "manage_maintenance_schedule",
  MAINTENANCE_SCHEDULE_OVERRIDE: "override_maintenance_schedule_conflicts",
  MAINTENANCE_LIFECYCLE_PROPOSE: "propose_maintenance_lifecycle",
  MAINTENANCE_LIFECYCLE_APPROVE: "approve_maintenance_lifecycle",
  MAINTENANCE_SERVICE_CONFIRM: "confirm_maintenance_service",
  GOVERNANCE_READ: "read_governance",
  GOVERNANCE_EXECUTE: "execute_governance",
  GOVERNANCE_INSPECT: "inspect_governance",
  GOVERNANCE_ASSIGN: "assign_governance",
  GOVERNANCE_TEMPLATES_MANAGE: "manage_governance_templates",
  GOVERNANCE_READINESS_OVERRIDE: "override_room_readiness",
  RESERVATION_RELOCATE: "relocate_reservation",
  USER_CREATE: "create_user",
  USER_READ: "read_user",
  USER_UPDATE: "update_user",
  USER_DELETE: "delete_user",
  ROLE_CREATE: "create_role",
  ROLE_READ: "read_role",
  ROLE_UPDATE: "update_role",
  ROLE_DELETE: "delete_role",
  PERMISSION_CREATE: "create_permission",
  PERMISSION_READ: "read_permission",
  PERMISSION_UPDATE: "update_permission",
  PERMISSION_DELETE: "delete_permission",
} as const;

export type PermissionName = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ADMIN_NAV_ITEMS = [
  {
    href: "/dashboard/hotels",
    label: "Hotéis",
    permission: PERMISSIONS.HOTEL_READ,
  },
  {
    href: "/dashboard/rooms",
    label: "Quartos",
    permission: PERMISSIONS.ROOM_READ,
  },
  {
    href: "/dashboard/customers",
    label: "Clientes",
    permission: PERMISSIONS.CUSTOMER_READ,
  },
  {
    href: "/dashboard/reservations",
    label: "Reservas",
    permission: PERMISSIONS.RESERVATIONS_CALENDAR_ACCESS,
  },
  {
    href: "/dashboard/transactions",
    label: "Painel financeiro",
    permission: PERMISSIONS.TRANSACTION_READ,
  },
  {
    href: "/dashboard/products",
    label: "Produtos",
    permission: PERMISSIONS.PRODUCT_READ,
  },
  {
    href: "/dashboard/consumption",
    label: "Vendas e consumo",
    permission: PERMISSIONS.CONSUMPTION_READ,
  },
  {
    href: "/dashboard/inventory",
    label: "Estoque",
    permission: PERMISSIONS.INVENTORY_READ,
  },
  {
    href: "/dashboard/procurement",
    label: "Compras",
    permission: PERMISSIONS.PROCUREMENT_READ,
  },
  {
    href: "/dashboard/organizations",
    label: "Organizações",
    permission: PERMISSIONS.BUSINESS_ORGANIZATIONS_READ,
  },
  {
    href: "/dashboard/cash",
    label: "Caixa e fechamento",
    permission: PERMISSIONS.CASH_MANAGEMENT_READ,
  },
  {
    href: "/dashboard/seasons",
    label: "Temporadas",
    permission: PERMISSIONS.SEASON_READ,
  },
  {
    href: "/dashboard/season-room-rates",
    label: "Tarifas por Temporada",
    permission: PERMISSIONS.SEASON_ROOM_RATE_READ,
  },
  {
    href: "/dashboard/maintenance",
    label: "Manutenção",
    permission: PERMISSIONS.MAINTENANCE_READ,
  },
  {
    href: "/dashboard/governance",
    label: "Governança",
    permission: PERMISSIONS.GOVERNANCE_READ,
  },
  {
    href: "/dashboard/users",
    label: "Usuários",
    permission: PERMISSIONS.USER_READ,
  },
  {
    href: "/dashboard/roles",
    label: "Roles",
    permission: PERMISSIONS.ROLE_READ,
  },
  {
    href: "/dashboard/permissions",
    label: "Permissões",
    permission: PERMISSIONS.PERMISSION_READ,
  },
] as const;
