-- Stage 6.2: declared guest preferences and secure pre-arrival workflow.
create extension if not exists pgcrypto with schema extensions;
alter table public.customers drop constraint if exists customers_document_type_document_number_key;
create unique index if not exists customers_hotel_document_normalized_key on public.customers(hotel_id,lower(btrim(document_type)),regexp_replace(lower(document_number),'[^a-z0-9]','','g'));

create table public.customer_preferences(
 id uuid primary key default gen_random_uuid(), hotel_id uuid not null references public.hotels(id), customer_id uuid not null,
 category text not null check(category in('room','service','food','accessibility','communication','other')), value text not null,
 source text not null check(source in('guest','staff')), consent_version text not null, confirmed_at timestamptz not null default now(),
 valid_until date, revoked_at timestamptz, created_by uuid, created_at timestamptz not null default now(),
 foreign key(customer_id,hotel_id) references public.customers(id,hotel_id)
);
create table public.reservation_guests(
 id uuid primary key default gen_random_uuid(), hotel_id uuid not null references public.hotels(id), reservation_id uuid not null,
 accommodation_id uuid, customer_id uuid, role text not null check(role in('primary','companion')), full_name text not null,
 document_type text, document_number text, birth_date date, email text, phone text, version integer not null default 1,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(id,hotel_id),
 foreign key(reservation_id,hotel_id) references public.reservations(id,hotel_id), foreign key(accommodation_id,hotel_id) references public.reservation_accommodations(id,hotel_id), foreign key(customer_id,hotel_id) references public.customers(id,hotel_id)
);
create table public.prearrival_access_tokens(
 id uuid primary key default gen_random_uuid(), hotel_id uuid not null references public.hotels(id), reservation_id uuid not null,
 token_hash text not null unique, expires_at timestamptz not null, revoked_at timestamptz, last_used_at timestamptz,
 created_by uuid, created_at timestamptz not null default now(), foreign key(reservation_id,hotel_id) references public.reservations(id,hotel_id)
);
create table public.prearrival_submissions(
 id uuid primary key default gen_random_uuid(), hotel_id uuid not null references public.hotels(id), reservation_id uuid not null,
 version integer not null, reservation_version integer not null, arrival_time time, payload jsonb not null, submitted_at timestamptz not null default now(),
 unique(reservation_id,version), foreign key(reservation_id,hotel_id) references public.reservations(id,hotel_id)
);
create table public.prearrival_requests(
 id uuid primary key default gen_random_uuid(), hotel_id uuid not null references public.hotels(id), reservation_id uuid not null,
 accommodation_id uuid, type text not null check(type in('special','amendment','cancellation')),
 category text not null, description text not null, status text not null default 'open' check(status in('open','triaged','accepted','rejected','converted','resolved','canceled')),
 assignee_id uuid, next_action text, due_at timestamptz, version integer not null default 1,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 foreign key(reservation_id,hotel_id) references public.reservations(id,hotel_id), foreign key(accommodation_id,hotel_id) references public.reservation_accommodations(id,hotel_id)
);
create table public.prearrival_request_events(
 id uuid primary key default gen_random_uuid(), hotel_id uuid not null references public.hotels(id), request_id uuid not null references public.prearrival_requests(id),
 action text not null, actor_id uuid, reason text, details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);

create function public.get_guest_relationship(p_hotel_id uuid,p_customer_id uuid,p_include_sensitive boolean default false) returns jsonb language sql stable set search_path=public as $$
 select jsonb_build_object('customer',to_jsonb(c),'preferences',coalesce((select jsonb_agg(to_jsonb(p) order by p.created_at desc) from public.customer_preferences p where p.customer_id=c.id and p.hotel_id=c.hotel_id and p.revoked_at is null and (p_include_sensitive or p.category not in('food','accessibility'))),'[]'),'reservations',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'code',r.reservation_code,'status',r.lifecycle_status,'created_at',r.created_at) order by r.created_at desc) from public.reservations r where r.hotel_id=c.hotel_id and (r.booking_customer_id=c.id or exists(select 1 from public.reservation_guests g where g.reservation_id=r.id and g.customer_id=c.id))),'[]'),'stays',coalesce((select jsonb_agg(jsonb_build_object('id',s.id,'status',s.stay_status,'checkin',s.checkin_date_expected,'checkout',s.checkout_date_expected) order by s.checkin_date_expected desc) from public.stays s join public.reservations r on r.id=s.reservation_id where r.hotel_id=c.hotel_id and (r.booking_customer_id=c.id or exists(select 1 from public.stay_customers sc where sc.stay_id=s.id and sc.customer_id=c.id))),'[]'),'requests',coalesce((select jsonb_agg(to_jsonb(q) order by q.created_at desc) from public.prearrival_requests q where q.hotel_id=c.hotel_id and exists(select 1 from public.reservation_guests g where g.reservation_id=q.reservation_id and g.customer_id=c.id)),'[]')) from public.customers c where c.id=p_customer_id and c.hotel_id=p_hotel_id $$;
create function public.save_guest_preference(p_hotel_id uuid,p_customer_id uuid,p_actor_id uuid,p_input jsonb) returns jsonb language plpgsql set search_path=public as $$declare v_id uuid;begin
 if not exists(select 1 from public.customers where id=p_customer_id and hotel_id=p_hotel_id) then return jsonb_build_object('result','not_found');end if;
 if length(trim(p_input->>'value'))<2 or length(trim(p_input->>'consent_version'))<1 then return jsonb_build_object('result','invalid');end if;
 insert into public.customer_preferences(hotel_id,customer_id,category,value,source,consent_version,valid_until,created_by) values(p_hotel_id,p_customer_id,p_input->>'category',trim(p_input->>'value'),p_input->>'source',trim(p_input->>'consent_version'),nullif(p_input->>'valid_until','')::date,p_actor_id) returning id into v_id;return jsonb_build_object('result','ok','id',v_id);end$$;
create function public.create_prearrival_link(p_hotel_id uuid,p_reservation_id uuid,p_actor_id uuid,p_hours integer) returns jsonb language plpgsql security definer set search_path=public,extensions as $$declare v_token text:=encode(gen_random_bytes(32),'hex');v_id uuid;begin
 if not exists(select 1 from public.reservations where id=p_reservation_id and hotel_id=p_hotel_id) then return jsonb_build_object('result','not_found');end if;
 update public.prearrival_access_tokens set revoked_at=now() where reservation_id=p_reservation_id and revoked_at is null;
 insert into public.prearrival_access_tokens(hotel_id,reservation_id,token_hash,expires_at,created_by) values(p_hotel_id,p_reservation_id,encode(digest(v_token,'sha256'),'hex'),now()+make_interval(hours=>p_hours),p_actor_id) returning id into v_id;
 return jsonb_build_object('result','ok','id',v_id,'token',v_token,'expires_at',now()+make_interval(hours=>p_hours));end$$;
create function public.resolve_prearrival_token(p_token text) returns jsonb language plpgsql security definer set search_path=public,extensions as $$declare t public.prearrival_access_tokens;r jsonb;begin
 select * into t from public.prearrival_access_tokens where token_hash=encode(digest(p_token,'sha256'),'hex') and revoked_at is null and expires_at>now();if not found then return jsonb_build_object('result','invalid_access');end if;
 update public.prearrival_access_tokens set last_used_at=now() where id=t.id;
 select jsonb_build_object('result','ok','access_id',t.id,'reservation',jsonb_build_object('id',x.id,'reservation_code',x.reservation_code,'version',x.version,'lifecycle_status',x.lifecycle_status),'hotel',(select jsonb_build_object('name',h.name,'slug',h.slug,'checkin_time',h.checkin_time_start) from public.hotels h where h.id=x.hotel_id),'accommodations',(select coalesce(jsonb_agg(jsonb_build_object('id',a.id,'room_type',a.room_type,'checkin_date',a.checkin_date,'checkout_date',a.checkout_date,'adults',a.adults,'children',a.children,'total_price',a.total_price)),'[]') from public.reservation_accommodations a where a.reservation_id=x.id and a.status not in('canceled','no_show')),'contact',(select to_jsonb(c) from public.reservation_contacts c where c.reservation_id=x.id),'requests',(select coalesce(jsonb_agg(to_jsonb(q) order by q.created_at desc),'[]') from public.prearrival_requests q where q.reservation_id=x.id)) into r from public.reservations x where x.id=t.reservation_id;return r;end$$;
create function public.submit_prearrival(p_token text,p_input jsonb) returns jsonb language plpgsql security definer set search_path=public,extensions as $$declare t public.prearrival_access_tokens;r public.reservations;v_version integer;g jsonb;q jsonb;begin
 select * into t from public.prearrival_access_tokens where token_hash=encode(digest(p_token,'sha256'),'hex') and revoked_at is null and expires_at>now() for update;if not found then return jsonb_build_object('result','invalid_access');end if;select * into r from public.reservations where id=t.reservation_id for update;
 if r.version<>(p_input->>'expected_version')::integer then return jsonb_build_object('result','conflict','context',jsonb_build_object('reservation_version',r.version));end if;
 select coalesce(max(version),0)+1 into v_version from public.prearrival_submissions where reservation_id=r.id;insert into public.prearrival_submissions(hotel_id,reservation_id,version,reservation_version,arrival_time,payload) values(r.hotel_id,r.id,v_version,r.version,nullif(p_input->>'arrival_time','')::time,p_input);
 if p_input?'primary_guest' then insert into public.reservation_guests(hotel_id,reservation_id,role,full_name,document_type,document_number,birth_date) values(r.hotel_id,r.id,'primary',p_input->'primary_guest'->>'full_name',p_input->'primary_guest'->>'document_type',p_input->'primary_guest'->>'document_number',(p_input->'primary_guest'->>'birth_date')::date) on conflict do nothing;end if;
 for g in select * from jsonb_array_elements(coalesce(p_input->'companions','[]')) loop insert into public.reservation_guests(hotel_id,reservation_id,accommodation_id,role,full_name,document_type,document_number,birth_date) values(r.hotel_id,r.id,(g->>'accommodation_id')::uuid,'companion',g->>'full_name',nullif(g->>'document_type',''),nullif(g->>'document_number',''),nullif(g->>'birth_date','')::date);end loop;
 for q in select * from jsonb_array_elements(coalesce(p_input->'requests','[]')) loop insert into public.prearrival_requests(hotel_id,reservation_id,accommodation_id,type,category,description,due_at) values(r.hotel_id,r.id,nullif(q->>'accommodation_id','')::uuid,'special',q->>'category',trim(q->>'description'),(select min(checkin_date)::timestamptz from public.reservation_accommodations where reservation_id=r.id));end loop;
 update public.prearrival_access_tokens set last_used_at=now() where id=t.id;return jsonb_build_object('result','ok','version',v_version);end$$;
create function public.create_prearrival_change_request(p_token text,p_input jsonb) returns jsonb language plpgsql security definer set search_path=public,extensions as $$declare t public.prearrival_access_tokens;v_id uuid;begin
 select * into t from public.prearrival_access_tokens where token_hash=encode(digest(p_token,'sha256'),'hex') and revoked_at is null and expires_at>now();if not found then return jsonb_build_object('result','invalid_access');end if;
 insert into public.prearrival_requests(hotel_id,reservation_id,type,category,description,due_at) values(t.hotel_id,t.reservation_id,p_input->>'type',p_input->>'type',trim(p_input->>'description'),now()) returning id into v_id;return jsonb_build_object('result','ok','id',v_id);end$$;
create function public.list_prearrival_board(p_hotel_id uuid) returns jsonb language sql stable set search_path=public as $$select jsonb_build_object('requests',coalesce((select jsonb_agg(to_jsonb(q)||jsonb_build_object('reservation_code',r.reservation_code,'arrival',(select min(checkin_date) from public.reservation_accommodations where reservation_id=r.id)) order by q.due_at nulls last) from public.prearrival_requests q join public.reservations r on r.id=q.reservation_id where q.hotel_id=p_hotel_id and q.status not in('resolved','rejected','canceled')),'[]'),'unassigned_arrivals',coalesce((select jsonb_agg(jsonb_build_object('reservation_id',a.reservation_id,'accommodation_id',a.id,'room_type',a.room_type,'arrival',a.checkin_date,'adults',a.adults,'children',a.children) order by a.checkin_date) from public.reservation_accommodations a where a.hotel_id=p_hotel_id and a.status='confirmed' and a.assigned_room_id is null and a.checkin_date<=current_date+1),'[]'))$$;
create function public.act_prearrival_request(p_hotel_id uuid,p_id uuid,p_actor_id uuid,p_input jsonb) returns jsonb language plpgsql set search_path=public as $$declare q public.prearrival_requests;v_status text;begin select * into q from public.prearrival_requests where id=p_id and hotel_id=p_hotel_id for update;if not found then return jsonb_build_object('result','not_found');end if;if q.version<>(p_input->>'expected_version')::integer then return jsonb_build_object('result','conflict','context',to_jsonb(q));end if;v_status=case p_input->>'action' when 'triage' then 'triaged' when 'accept' then 'accepted' when 'reject' then 'rejected' when 'convert' then 'converted' when 'resolve' then 'resolved' when 'cancel' then 'canceled' end;if v_status is null or length(trim(p_input->>'reason'))<3 then return jsonb_build_object('result','invalid');end if;update public.prearrival_requests set status=v_status,assignee_id=coalesce(nullif(p_input->>'assignee_id','')::uuid,assignee_id),next_action=nullif(trim(p_input->>'next_action'),''),version=version+1,updated_at=now() where id=p_id;insert into public.prearrival_request_events(hotel_id,request_id,action,actor_id,reason,details) values(p_hotel_id,p_id,p_input->>'action',p_actor_id,trim(p_input->>'reason'),p_input);return jsonb_build_object('result','ok','id',p_id);end$$;

alter table public.operational_pending drop constraint operational_pending_source_check;
alter table public.operational_pending add constraint operational_pending_source_check check(source in('maintenance','consumption','governance','inventory','procurement','cash','partner','reservations','booking_channels'));
alter function public.operational_pending_candidates(uuid,timestamptz) rename to operational_pending_candidates_stage6_base;
create function public.operational_pending_candidates(p_hotel_id uuid,p_now timestamptz default now()) returns jsonb language plpgsql set search_path=public as $$declare v jsonb;begin v:=public.operational_pending_candidates_stage6_base(p_hotel_id,p_now);
 v:=v||coalesce((select jsonb_agg(jsonb_build_object('source','reservations','source_key','prearrival:'||q.id,'kind',q.type,'entity_type','prearrival_request','entity_id',q.id,'title','Pré-chegada: '||replace(q.category,'_',' '),'href','/dashboard/reservations/prearrival','severity',case when q.due_at<=p_now then 'critical' else 'warning' end,'assignee_id',q.assignee_id,'due_at',q.due_at)) from public.prearrival_requests q where q.hotel_id=p_hotel_id and q.status in('open','triaged','accepted')),'[]');
 v:=v||coalesce((select jsonb_agg(jsonb_build_object('source','reservations','source_key','unassigned:'||a.id,'kind','unassigned_arrival','entity_type','reservation_accommodation','entity_id',a.id,'title','Chegada próxima sem quarto','href','/dashboard/reservations/prearrival','severity','critical','due_on',a.checkin_date)) from public.reservation_accommodations a where a.hotel_id=p_hotel_id and a.status='confirmed' and a.assigned_room_id is null and a.checkin_date<=((p_now at time zone (select timezone from public.hotels where id=p_hotel_id))::date+1)),'[]');return v;end$$;
alter function public.can_read_operational_pending(public.operational_pending,uuid,text[]) rename to can_read_operational_pending_stage6_base;
create function public.can_read_operational_pending(p public.operational_pending,p_user_id uuid,p_permissions text[]) returns boolean language sql stable set search_path=public as $$select case when p.source in('reservations','booking_channels') then p_permissions&&array['read_reservation','manage_prearrival','manage_booking_channels'] else public.can_read_operational_pending_stage6_base(p,p_user_id,p_permissions) end$$;

insert into public.permissions(name,type) select name,'HOTEL_PERMISSION' from unnest(array['read_guest_relationship','manage_guest_relationship','manage_prearrival']) name on conflict(name) do nothing;
do $$declare t text;begin foreach t in array array['customer_preferences','reservation_guests','prearrival_access_tokens','prearrival_submissions','prearrival_requests','prearrival_request_events'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated',t);execute format('grant all on public.%I to service_role',t);end loop;end$$;
grant execute on function public.get_guest_relationship(uuid,uuid,boolean),public.save_guest_preference(uuid,uuid,uuid,jsonb),public.create_prearrival_link(uuid,uuid,uuid,integer),public.resolve_prearrival_token(text),public.submit_prearrival(text,jsonb),public.create_prearrival_change_request(text,jsonb),public.list_prearrival_board(uuid),public.act_prearrival_request(uuid,uuid,uuid,jsonb),public.operational_pending_candidates(uuid,timestamptz),public.can_read_operational_pending(public.operational_pending,uuid,text[]) to service_role;
